### ISSUE TITLE
beanborg.handlers.amount_handler not shipped with package

### ISSUE THREAD

**Issue by berkes** [luciano-fiandesio/beanborg#19]
I installed beanborg from github as per instructions: `pip install git+https://github.com/luciano-fiandesio/beanborg.git`

But, somehow the `handlers` aren't present in the local files:
```
Permissions Size User Date Modified Name
drwxrwxr-x     - [REDACTED]   3 okt 13:12 [REDACTED]/.local/lib/python3.10/site-packages/beanborg/
.rw-rw-r--     0 [REDACTED]   3 okt 13:12  ├── __init__.py
drwxrwxr-x     - [REDACTED]   3 okt 13:12  ├── __pycache__/
.rw-rw-r--   159 [REDACTED]   3 okt 13:12  │  ├── __init__.cpython-310.pyc
.rw-rw-r--   562 [REDACTED]   3 okt 13:12  │  ├── arg_parser.cpython-310.pyc
.rw-rw-r--  1,7k [REDACTED]   3 okt 13:12  │  ├── bb_archive.cpython-310.pyc
.rw-rw-r--  8,3k [REDACTED]   3 okt 13:12  │  ├── bb_import.cpython-310.pyc
.rw-rw-r--  1,9k [REDACTED]   3 okt 13:12  │  ├── bb_mover.cpython-310.pyc
.rw-rw-r--  3,3k [REDACTED]   3 okt 13:12  │  └── config.cpython-310.pyc
.rw-rw-r--   411 [REDACTED]   3 okt 13:12  ├── arg_parser.py
.rw-rw-r--  1,7k [REDACTED]   3 okt 13:12  ├── bb_archive.py
.rw-rw-r--   12k [REDACTED]   3 okt 13:12  ├── bb_import.py
.rw-rw-r--  2,4k [REDACTED]   3 okt 13:12  ├── bb_mover.py
.rw-rw-r--  3,8k [REDACTED]   3 okt 13:12  ├── config.py
drwxrwxr-x     - [REDACTED]   3 okt 13:12  └── rule_engine/
.rw-rw-r--     0 [REDACTED]   3 okt 13:12     ├── __init__.py
drwxrwxr-x     - [REDACTED]   3 okt 13:12     ├── __pycache__/
.rw-rw-r--   171 [REDACTED]   3 okt 13:12     │  ├── __init__.cpython-310.pyc
.rw-rw-r--   672 [REDACTED]   3 okt 13:12     │  ├── Context.cpython-310.pyc
.rw-rw-r--  2,2k [REDACTED]   3 okt 13:12     │  ├── decision_tables.cpython-310.pyc
.rw-rw-r--  9,3k [REDACTED]   3 okt 13:12     │  ├── rules.cpython-310.pyc
.rw-rw-r--  3,5k [REDACTED]   3 okt 13:12     │  └── rules_engine.cpython-310.pyc
.rw-rw-r--   975 [REDACTED]   3 okt 13:12     ├── Context.py
.rw-rw-r--  2,0k [REDACTED]   3 okt 13:12     ├── decision_tables.py
.rw-rw-r--  9,4k [REDACTED]   3 okt 13:12     ├── rules.py
.rw-rw-r--  4,1k [REDACTED]   3 okt 13:12     └── rules_engine.py
```

I think this is what causes the following error when running `bb_import -f /my/config.yml`:

```
Traceback (most recent call last):
  File "[REDACTED]/.local/bin/bb_import", line 5, in <module>
    from beanborg import bb_import
  File "[REDACTED]/.local/lib/python3.10/site-packages/beanborg/bb_import.py", line 24, in <module>
    from beanborg.handlers.amount_handler import AmountHandler
ModuleNotFoundError: No module named 'beanborg.handlers'
```

I searched through the source to see what makes that files are in- or excluded, but saw nothing. I'm not very familiar with python, pip or setuptools(?). I presume this dir needs to be included explicitly somehow?

**Comment by luciano-fiandesio** [comment]
Argh, let me check..
