### ISSUE TITLE
Tutorial: actual results differ from description

### ISSUE THREAD

**Issue by workflowsguy** [luciano-fiandesio/beanborg#6]
Hello,

trying to follow the `beanborg` tutorial, I ran into the following issues:

1) several of the `bb_` commands incorrectly are shown with a `.csv` extension.

2) After running `bb_import` for the first time, there is not just a simply error message shown, but a complete traceback
```
Traceback (most recent call last):
  File "/Users/guy/Library/Python/3.8/bin/bb_import", line 8, in <module>
    sys.exit(bb_import.main())
  File "/Users/guy/Library/Python/3.8/lib/python/site-packages/beanborg/bb_import.py", line 145, in main
    rule_engine = init_rule_engine(args)
  File "/Users/guy/Library/Python/3.8/lib/python/site-packages/beanborg/bb_import.py", line 51, in init_rule_engine
    return RuleEngine(
  File "/Users/guy/Library/Python/3.8/lib/python/site-packages/beanborg/rule_engine/rules_engine.py", line 80, in __init__
    custom_rules = self.load_custom_rules()
  File "/Users/guy/Library/Python/3.8/lib/python/site-packages/beanborg/rule_engine/rules_engine.py", line 137, in load_custom_rules
    os.listdir(os.getcwd() + "/" + self._ctx.rules_dir), "*.py"
FileNotFoundError: [Errno 2] No such file or directory: '/Users/guy/Documents/beanborg/beanborg/rules'
```

3) After creating `account.rules` and running `bb_import -f config/eagle.yaml` again, the message
```
file: rules/asset.rules does not exist! - The 'Replace_Asset' rules requires the asset.rules file.
```
is displayed even though there is no `Replace_Asset`rule defined in `eagle.yaml`.

4) When I put the `- name: Set_Accounts` rule into `eagle.yaml` and then run `bb_import -f config/eagle.yaml`, it returns a traceback, ending in
```
yaml.scanner.ScannerError: mapping values are not allowed here
  in "config/eagle.yaml", line 22, column 17
```

**Comment by luciano-fiandesio** [comment]
I have fixed the tutorial, sorry about the mistakes.
Regarding (3), the `Replace_Asset` rule is automatically added to the list of rules, even if it's not specified explicitly.
Regarding (4), it may be a problem with indentation. I wasn't able to reproduce.
